
/** @file
  This file defines the EFI_REDFISH_PLATFORM_BIOS_RESOURCE
  protocol.

  (C) Copyright 2019 Hewlett Packard Enterprise Development LP<BR>

  SPDX-License-Identifier: BSD-2-Clause-Patent

**/

#ifndef EFI_REDFISH_PLATFORM_BIOS_RESOURCE_H_
#define EFI_REDFISH_PLATFORM_BIOS_RESOURCE_H_

#include <Library/BaseJsonLib.h>

typedef struct _EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL;
typedef struct _EFI_REDFISH_PLATFORM_BIOS_RESOURCE_HEADER EFI_REDFISH_PLATFORM_BIOS_RESOURCE_HEADER;

#define EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL_GUID \
    {  \
      0x81C84065, 0x41D8, 0x3B38, 0x87, 0x09, 0x36, 0x99, 0xD1, 0x2B, 0xE4, 0x49 }  \
    }

typedef enum {
  EfiRedfishPlatformBiosResourceTypeNone = 0,
  EfiRedfishPlatformBiosResourceTypeComputerSystemId,      ///< v1.0, the ID of computer system instance.
  EfiRedfishPlatformBiosResourceTypeComputerSystemUri,     ///< v1.0, Retrieve Platform ComputerSystem resource URI.
  EfiRedfishPlatformBiosResourceTypeBiosUri,               ///< v1.0, Retrieve Platform BIOS resource URI.
  EfiRedfishPlatformBiosSettingUri,                        ///< v1.0, Retrieve Platform BIOS future setting URI.
  EfiRedfishPlatformBiosResourceTypeAttributeRegistryUri,  ///< v1.0, Retrieve Platform BIOS
                                                           ///< Attribute Registry resource URI.
  EfiRedfishPlatformBiosResourceTypeAttributeRegistryId ,  ///< v1.0, ID of Attribute Registry.
  EfiRedfishPlatformBiosResourceTypeBios,                  ///< v1.0, Retrieve Platform BIOS resource.
  EfiRedfishPlatformBiosResourceTypeAttributeRegistry      ///< v1.0, Retrieve Platform BIOS
                                                           ///< Attribute Registry resource.
} EFI_REDFISH_PLATFORM_BIOS_RESOURCE_TYPE;

typedef enum {
  EfiRedfishPlatformBiosResourceNone = 0,            ///< No merge type.
  EfiRedfishPlatformBiosResourceMergeToPlainText,    ///< v1.0, Merge Redfish platform BIOS resource with
                                                     ///< EDK2 EFI Redfish BIOS feature driver.
  EfiRedfishPlatformBiosResourceOverrideByPlainText, ///< v1.0, Use Redfish platform BIOS resource and discard
                                                     ///< the resource generasted by EDK2 EFI Redfish BIOS
                                                     ///< feature driver.
  EfiRedfishPlatformBiosResourceMergeToUri,          ///< v1.0, Resource alread in Redfish service. Merge with
                                                     ///< resource generasted by EDK2 EFI Redfish BIOS
                                                     ///< feature driver.
  EfiRedfishPlatformBiosResourceOverrideByUri        ///< v1.0, Use entire resource which is alread in Redfish service.
} EFI_REDFISH_PLATFORM_BIOS_RESOURCE_MERGE_TYPE;

typedef enum {
  EfiRedfishPlatformBiosValueTypeNull = 0,   ///< Value is NULL.
  EfiRedfishPlatformBiosValueTypeNumber,     ///< Value type is number.
  EfiRedfishPlatformBiosValueTypeString,     ///< Value type is string.
  EfiRedfishPlatformBiosValueTypeBoolean,    ///< Value type is boolean.
  EfiRedfishPlatformBiosValueTypeEnumeration ///< Value type is enumeration.
} EFI_REDFISH_PLATFORM_BIOS_VALUE_TYPE;

/**
  Get platform BIOS resource such as BIOS Attribute Registry or BIOS resource.

  This function will be called by the EDK2 EFI Redfish BIOS feature driver to retrieve the
  BIOS Attribute Registry resource.

  @param[in]   This                    Pointer to EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL
                                       instance.
  @param[in]   ResourceType            Redfish BIOS resource to retrieve.
  @param[out]  MergeType               The way to merge platform BIOS resource with the
                                       resource generated by EDK2 EFI Redfish BIOS feature driver.
                                       MergeType could be NULL indicates caller doesn't
                                       this information.
  @param[out]  ResourceJson            Resource in JSON format.
                                       ResourceJson could be NULL depends on the ResourceType.
                                       Or ResourceJson could be NULL indicates caller doesn't
                                       this information.
  @param[out]  ResourceSize            Size of resource, could be NULL depends on the ResourceType.
                                       Or ResourceSize could be NULL indicates caller doesn't
                                       this information.
  @param[out]  ResourceUri             Full URI to this resource in Redfish service.
                                       ResourceUri could be NULL depends on the ResourceType.

  If ResourceType is nay of below values, then MergeType, ResourceJson and ResourceSize may returned
  with platform Redfish BIOS resource information.
     - EfiRedfishPlatformBiosResourceTypeAttributeRegistry
     - EfiRedfishPlatformBiosResourceTypeBios

  If ResourceType is nay of below values, then ResourceUri is retured with the URI to
  platform Redfish BIOS resource.
   - EfiRedfishPlatformBiosResourceTypeAttributeRegistryUri
   - EfiRedfishPlatformBiosResourceTypeBiosUri
   - EfiRedfishPlatformBiosResourceTypeComputerSystemUri

  That is caller's responsibility to free memory pool of ResourceJson or ResourceUri f those are
  not returned in NULL.

  @retval EFI_SUCCESS                  The BIOS resource information is returned.
  @retval EFI_UNSUPPORTED              No BIOS resource information of tyep indicated in ResourceType.
  @retval Other                        Error happens during the initialization.

**/
typedef
EFI_STATUS
(EFIAPI *EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL_GET) (
  IN  EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL *This,
  IN  EFI_REDFISH_PLATFORM_BIOS_RESOURCE_TYPE       ResourceType,
  OUT EFI_REDFISH_PLATFORM_BIOS_RESOURCE_MERGE_TYPE *MergeType OPTIONAL,
  OUT CHAR8  **ResourceJson OPTIONAL,
  OUT UINTN  *ResourceSize OPTIONAL,
  OUT CHAR8  **ResourceUri OPTIONAL
  );

/**
  Apply BIOS Attribute value through platform funtion

  This function will be called by the EDK2 EFI Redfish BIOS feature driver.

  @param[in]   This                    Pointer to EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL
                                       instance.
  @param[in]   AttributeName           Pointer to BIOS Attribute name.
  @param[in]   ValueType               Value type of this BIOS Attribute.
  @param[in]   Value                   Pointer to the value in ValueLength size.
  @param[in]   ValueLength             Length of bytes of BIOS Attribute value.

  @retval EFI_SUCCESS                  Platform processe for this BIOS attribute has been processed.
                                       EDK2 EFI Redfish BIOS feature driver can have further processes.
  @retval EFI_UNSUPPORTED              No platform processes for this. Edk2 EFI Redfish BIOS feature
                                       driver can have further processes.
  @retval Other                        Error happens during the initialization.

**/
typedef
EFI_STATUS
(EFIAPI *EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL_APPLY_ATTRIBUTE) (
  IN  EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL *This,
  IN  CHAR8  *AttributeName,
  IN  EFI_REDFISH_PLATFORM_BIOS_VALUE_TYPE ValueType,
  IN  VOID *Value,
  IN  UINTN ValueLength
  );

/**
  Get BIOS Attribute value through platform funtion

  This function will be called by the EDK2 EFI Redfish BIOS feature driver.

  @param[in]   This                    Pointer to EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL
                                       instance.
  @param[in]   AttributeName           Pointer to BIOS Attribute name.
  @param[in]   AttributeValue          Pointer to retrieve BIOS Attribute in string,
  @param[in]   Length                  Pointer to retrieve the length of AttributeValue.

  @retval EFI_SUCCESS                  Platform processe for this BIOS attribute has been processed.
                                       EDK2 EFI Redfish BIOS feature driver can have further processes.
  @retval EFI_UNSUPPORTED              No platform processes for this. Edk2 EFI Redfish BIOS feature
                                       driver can have further processes.
  @retval Other                        Error happens during the initialization.

**/
typedef
EFI_STATUS
(EFIAPI *EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL_GET_ATTRIBUTE) (
  IN   EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL *This,
  IN   CONST CHAR8 *AttributeName,
  OUT  VOID        **AttributeValue,
  OUT  UINTN       *AttributeValueLength
  );

/**
  Add/modify platform specific AttributeRegistry properties.

  This function will be called by the EDK2 EFI Redfish BIOS feature driver.

  @param[in]   This             Pointer to EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL instance.
  @param[in]   AttrRegObject   Pointer to JSON object on which platform properties can be added.


  @retval EFI_SUCCESS           Platform BIOS resource information returned.
  @retval Other                 Errors happened.

**/
typedef
EFI_STATUS
(EFIAPI *EFI_REDFISH_PLATFORM_ADD_ATTRIBUTE_REGISTRY_PROPERTIES) (
  IN  EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL *This,
  IN  EDKII_JSON_OBJECT *AttrRegObject
  );

/**
  Add/modify platform specific BIOS properties.

  This function will be called by the EDK2 EFI Redfish BIOS feature driver.

  @param[in]   This             Pointer to EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL instance.
  @param[in]   biosJsonObject    Pointer to JSON object on which platform properties can be added.


  @retval EFI_SUCCESS           Platform BIOS resource information returned.
  @retval Other                 Errors happened.

**/
typedef
EFI_STATUS
(EFIAPI *EFI_REDFISH_PLATFORM_ADD_BIOS_PROPERTIES) (
  IN  EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL *This,
  IN  EDKII_JSON_OBJECT *BiosObject
  );

struct _EFI_REDFISH_PLATFORM_BIOS_RESOURCE_HEADER {
  UINT8   Major;        ///< Major version of EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL
  UINT8   Minor;        ///< Minor version of EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL
};

struct _EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL {
  EFI_REDFISH_PLATFORM_BIOS_RESOURCE_HEADER                   Header;
  EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL_GET             GetRedfishBiosResource;
  EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL_APPLY_ATTRIBUTE ApplyRedfishBiosAttributeValue;
  EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL_GET_ATTRIBUTE   GetRedfishBiosAttributeValue;
  EFI_REDFISH_PLATFORM_ADD_ATTRIBUTE_REGISTRY_PROPERTIES      AddAttributeRegistryProperties;
  EFI_REDFISH_PLATFORM_ADD_BIOS_PROPERTIES                    AddBiosProperties;
};

extern EFI_GUID gEfiRedfishPlatformBiosResourceProtocolGuid;

#endif
