/** @file
  Provide Redfish platform BIOS resource information throught
  EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL.

  (C) Copyright 2020 Hewlett Packard Enterprise Development LP<BR>

  SPDX-License-Identifier: BSD-2-Clause-Patent

**/

#include <RedfishPlatformBiosResourceDxe.h>

/**
  Get platform BIOS resource such as BIOS Attribute Registry or BIOS resource.

  This function will be called by the EDK2 EFI Redfish BIOS feature driver to retrieve the
  BIOS Attribute Registry resource.

  @param[in]   This                    Pointer to EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL
                                       instance.
  @param[in]   ResourceType            Redfish BIOS resource to retrieve.
  @param[out]  MergeType               The way to merge platform BIOS resource with the
                                       resource generated by EDK2 EFI Redfish BIOS feature driver.
                                       MergeType could be NULL indicates caller doesn't
                                       this information.
  @param[out]  ResourceJson            Resource in JSON format.
                                       ResourceJson could be NULL depends on the ResourceType.
                                       Or ResourceJson could be NULL indicates caller doesn't
                                       this information.
  @param[out]  ResourceSize            Size of resource, could be NULL depends on the ResourceType.
                                       Or ResourceSize could be NULL indicates caller doesn't
                                       this information.
  @param[out]  ResourceUri             Full URI to this resource in Redfish service.
                                       ResourceUri could be NULL depends on the ResourceType.

  If ResourceType is nay of below values, then MergeType, ResourceJson and ResourceSize may returned
  with platform Redfish BIOS resource information.
     - EfiRedfishPlatformBiosResourceTypeAttributeRegistry
     - EfiRedfishPlatformBiosResourceTypeBios

  If ResourceType is nay of below values, then ResourceUri is retured with the URI to
  platform Redfish BIOS resource.
   - EfiRedfishPlatformBiosResourceTypeComputerSystemId, the string of Id of computer system instance.
   - EfiRedfishPlatformBiosResourceTypeAttributeRegistryUri
   - EfiRedfishPlatformBiosResourceTypeBiosUri
   - EfiRedfishPlatformBiosResourceTypeComputerSystemUri

  That is caller's responsibility to free memory pool of ResourceJson or ResourceUri f those are
  not returned in NULL.

  @retval EFI_SUCCESS                  The BIOS resource information is returned.
  @retval EFI_UNSUPPORTED              No BIOS resource information of type indicated in ResourceType.
  @retval Other                        Error happens during the initialization.

**/
EFI_STATUS
GetRedfishBiosResource (
  IN  EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL *This,
  IN  EFI_REDFISH_PLATFORM_BIOS_RESOURCE_TYPE       ResourceType,
  OUT EFI_REDFISH_PLATFORM_BIOS_RESOURCE_MERGE_TYPE *MergeType OPTIONAL,
  OUT CHAR8  **ResourceJson OPTIONAL,
  OUT UINTN  *ResourceSize OPTIONAL,
  OUT CHAR8  **ResourceUri OPTIONAL
  )
{
  CHAR8 *Temp;

  if (ResourceType == EfiRedfishPlatformBiosResourceTypeComputerSystemId) {
    if (ResourceUri == NULL) {
      return EFI_INVALID_PARAMETER;
    }
    Temp = (CHAR8 *)AllocateZeroPool (AsciiStrSize ("badfaced-aaaa-beef-1313-131313131313"));
    if (Temp == NULL) {
      return EFI_OUT_OF_RESOURCES;
    }
    AsciiStrCpyS (Temp, AsciiStrSize ("badfaced-aaaa-beef-1313-131313131313"), "badfaced-aaaa-beef-1313-131313131313");
    *ResourceUri = Temp;
    return EFI_SUCCESS;
  }
  return EFI_NOT_FOUND;
}

/**
  Apply BIOS Attribute Registry future settings through platform funtion if the specific
  platform processes are required before the setting is applied to HII.

  This function will be called by the EDK2 EFI Redfish BIOS feature driver.

  @param[in]   This                    Pointer to EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL
                                       instance.
  @param[in]   AttributeName           Pointer to BIOS Attribute name.
  @param[in]   ValueType               Value type of this BIOS Attribute.
  @param[in]   Value                   Pointer to the value in ValueLength size.
  @param[in]   ValueLength             Length of bytes of BIOS Attribute value.

  @retval EFI_SUCCESS                  Platform processe for this BIOS attribute has been processed.
                                       EDK2 EFI Redfish BIOS feature driver can have further processes.
  @retval EFI_UNSUPPORTED              No platform processes for this. Edk2 EFI Redfish BIOS feature
                                       driver can have further processes.
  @retval EFI_ALREADY_STARTED          Platform processe for this BIOS attribute has been processed.
                                       Skip further processes of EDK2 EFI Redfish BIOS feature driver.
  @retval Other                        Error happens during the initialization.

**/
EFI_STATUS
ApplyRedfishBiosValue (
  IN  EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL *This,
  IN  CHAR8  *AttributeName,
  IN  EFI_REDFISH_PLATFORM_BIOS_VALUE_TYPE ValueType,
  IN  VOID *Value,
  IN  UINTN ValueLength
  )
{
  return EFI_SUCCESS;
}

/**
  Get BIOS Attribute value through platform funtion

  This function will be called by the EDK2 EFI Redfish BIOS feature driver.

  @param[in]   This                    Pointer to EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL
                                       instance.
  @param[in]   AttributeName           Pointer to BIOS Attribute name.
  @param[in]   AttributeValue          Pointer to retrieve BIOS Attribute in string,
  @param[in]   Length                  Pointer to retrieve the length of AttributeValue.

  @retval EFI_SUCCESS                  Platform processe for this BIOS attribute has been processed.
                                       EDK2 EFI Redfish BIOS feature driver can have further processes.
  @retval EFI_UNSUPPORTED              No platform processes for this. Edk2 EFI Redfish BIOS feature
                                       driver can have further processes.
  @retval Other                        Error happens during the initialization.

**/
EFI_STATUS
GetRedfishBiosValue (
  IN  EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL *This,
  IN  CONST CHAR8 *AttributeName,
  OUT VOID        **AttributeValue,
  OUT UINTN       *AttributeValueLength
  )
{
  return EFI_UNSUPPORTED;
}

/**
  Add/modify platform specific AttributeRegistry properties.

  This function will be called by the EDK2 EFI Redfish BIOS feature driver.

  @param[in]   This             Pointer to EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL instance.
  @param[in]   AttrRegObject   Pointer to JSON object on which platform properties can be added.


  @retval EFI_SUCCESS           Platform BIOS resource information returned.
  @retval Other                 Errors happened.

**/
EFI_STATUS
AddAttributeRegistryProperties (
  IN  EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL *This,
  IN  EDKII_JSON_OBJECT *AttrRegObject
  )
{
  return EFI_UNSUPPORTED;
}

/**
  Add/modify platform specific BIOS properties.

  This function will be called by the EDK2 EFI Redfish BIOS feature driver.

  @param[in]   This             Pointer to EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL instance.
  @param[in]   biosJsonObject    Pointer to JSON object on which platform properties can be added.


  @retval EFI_SUCCESS           Platform BIOS resource information returned.
  @retval Other                 Errors happened.

**/
EFI_STATUS
AddBiosProperties (
  IN  EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL *This,
  IN  EDKII_JSON_OBJECT *BiosObject
  )
{
  return EFI_UNSUPPORTED;
}

EFI_REDFISH_PLATFORM_BIOS_RESOURCE_PROTOCOL mRedfishPlatformBiosResourceProtocol [] = {
  1, 0,
  GetRedfishBiosResource,
  ApplyRedfishBiosValue,
  GetRedfishBiosValue,
  AddAttributeRegistryProperties,
  AddBiosProperties
};

/**
  Main entry for this driver.

  @param ImageHandle     Image handle this driver.
  @param SystemTable     Pointer to SystemTable.

  @retval EFI_SUCESS     This function always complete successfully.

**/
EFI_STATUS
EFIAPI
RedfishPlatformBiosResourceDxeDriverEntryPoint (
  IN EFI_HANDLE         ImageHandle,
  IN EFI_SYSTEM_TABLE   *SystemTable
  )
{
  EFI_STATUS  Status;
  EFI_HANDLE  Handle;

  Handle = NULL;

  //
  // Install the RedfishCredentialProtocol onto Handle.
  //
  Status = gBS->InstallMultipleProtocolInterfaces (
                  &Handle,
                  &gEfiRedfishPlatformBiosResourceProtocolGuid,
                  &mRedfishPlatformBiosResourceProtocol,
                  NULL
                  );
  if (EFI_ERROR (Status)) {
    return Status;
  }
  return EFI_SUCCESS;
}
